### ISSUE TITLE
Changing attr name

### ISSUE THREAD

**Issue by spbisya** [durranilab/LabProgressLayout#1]
You need to change your attr name cornerRadius as it is conflicting with the resources of bottom navigation view.

<img width="1523" alt="Screen Shot 2019-04-07 at 10 50 00 AM" src="https://user-images.githubusercontent.com/13161250/55680504-ec50f700-5922-11e9-9dd4-8e32acddc647.png">

**Comment by durranilab** [comment]
Great, updating ASAP

**Comment by akrezic1** [comment]
@spbisya I created PR with fixes, you can use my forked lib with jitpack.io until it is merged. It is also updating minSdk to 21 because method used in this library requires it, so I guess it would crash in runtime on those devices.

**Comment by spbisya** [comment]
> @spbisya I created PR with fixes, you can use my forked lib with jitpack.io until it is merged. It is also updating minSdk to 21 because method used in this library requires it, so I guess it would crash in runtime on those devices.

thanks, I've already copied the sources and used them in my project directly with some other necessary changes.

**Comment by durranilab** [comment]
Pull Request Merged With Solution :)

**Comment by LunevNF** [comment]
Not working, no update in maven (1.0.4).
